name: compas-fs2021
channels:
    - conda-forge

dependencies:
   - python=3.8
   - pip
   - git
   - compas=1.*
   - compas_fab>=0.17.1
   - igl>=2.2.1
   - compas_cgal>=0.1.1
   - compas_rrc
   - compas_slicer
